Cording
Ryota-wata/mokumoku pull request #2
Opened 2023-05-07 12:43 UTC by Ryota-wata

卒業試験の実装課題について、ご確認お願い致します。

テスト
[![Image from Gyazo](https://i.gyazo.com/233adc78328f6014389de5ed87d1c60d.png)](https://gyazo.com/233adc78328f6014389de5ed87d1c60d)

2023-05-07 22:41 UTC, busitora requested changes

2023-05-07 22:41 UTC, busitora commented on app/models/user.rb
> +    relationships.find_by(followed_id: user_id).destroy
1. relationships.find_by(followed_id: user_id) 
2.  1で 値が nil になった場合、 nilに対して destroy でエラーが発生します

2023-05-08 01:24 UTC, Ryota-wata reviewed
ご指摘頂きありがとうございます。
relationshipがtrueの場合のみdestroyを実行するように修正しました。

ご確認よろしくお願い致します。

2023-05-08 10:12 UTC, busitora approved these changes
LGTM!

2023-05-15 12:04 UTC, merged